# Generated by Django 5.2 on 2025-05-04 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0038_alter_customuser_user_type_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="profile_pic",
            field=models.ImageField(
                blank=True, null=True, upload_to="media/profile_pic"
            ),
        ),
    ]
