# Generated by Django 5.2 on 2025-05-05 04:28

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0046_alter_customuser_profile_pic"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentresult",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="studentresult",
            name="end_sem_mark",
        ),
        migrations.RemoveField(
            model_name="studentresult",
            name="total_mark",
        ),
        migrations.RemoveField(
            model_name="studentresult",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="profile_pic",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
    ]
