# Generated by Django 5.2 on 2025-05-05 04:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0047_remove_studentresult_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentresult",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="studentresult",
            name="end_sem_mark",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="studentresult",
            name="total_mark",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="studentresult",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="staff_feedback",
            name="feedback_reply",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="student_feedback",
            name="feedback_reply",
            field=models.TextField(blank=True),
        ),
    ]
