# Generated by Django 5.2 on 2025-05-05 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0048_studentresult_created_at_studentresult_end_sem_mark_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="profile_pic",
            field=models.ImageField(blank=True, null=True, upload_to="profile_pic"),
        ),
        migrations.AlterField(
            model_name="staff_feedback",
            name="feedback_reply",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="student_feedback",
            name="feedback_reply",
            field=models.TextField(),
        ),
    ]
