# Generated by Django 5.2 on 2025-05-05 06:53

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0049_alter_customuser_profile_pic_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="profile_pic",
            field=models.ImageField(
                blank=True, null=True, upload_to=app.models.profile_pic_path
            ),
        ),
    ]
